// Code generated by protoc-gen-go.
// source: game.proto
// DO NOT EDIT!

/*
Package gameproto is a generated protocol buffer package.

It is generated from these files:
	game.proto

It has these top-level messages:
	Login
	Move
*/
package gameproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Login struct {
	Msgid            *int32 `protobuf:"varint,1,req,name=msgid,def=1001" json:"msgid,omitempty"`
	Name             *int32 `protobuf:"varint,2,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Login) Reset()                    { *m = Login{} }
func (m *Login) String() string            { return proto.CompactTextString(m) }
func (*Login) ProtoMessage()               {}
func (*Login) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_Login_Msgid int32 = 1001

func (m *Login) GetMsgid() int32 {
	if m != nil && m.Msgid != nil {
		return *m.Msgid
	}
	return Default_Login_Msgid
}

func (m *Login) GetName() int32 {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return 0
}

type Move struct {
	Msgid            *int32 `protobuf:"varint,1,req,name=msgid,def=1002" json:"msgid,omitempty"`
	X                *int32 `protobuf:"varint,2,req,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,3,req,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Move) Reset()                    { *m = Move{} }
func (m *Move) String() string            { return proto.CompactTextString(m) }
func (*Move) ProtoMessage()               {}
func (*Move) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

const Default_Move_Msgid int32 = 1002

func (m *Move) GetMsgid() int32 {
	if m != nil && m.Msgid != nil {
		return *m.Msgid
	}
	return Default_Move_Msgid
}

func (m *Move) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Move) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*Login)(nil), "gameproto.Login")
	proto.RegisterType((*Move)(nil), "gameproto.Move")
}

var fileDescriptor0 = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x4f, 0xcc, 0x4d,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0xb1, 0xc1, 0x4c, 0x25, 0x2d, 0x2e, 0x56,
	0x9f, 0xfc, 0xf4, 0xcc, 0x3c, 0x21, 0x61, 0x2e, 0xd6, 0xdc, 0xe2, 0xf4, 0xcc, 0x14, 0x09, 0x46,
	0x05, 0x26, 0x0d, 0x56, 0x2b, 0x16, 0x43, 0x03, 0x03, 0x43, 0x21, 0x1e, 0x2e, 0x96, 0x3c, 0xa0,
	0x52, 0x09, 0x26, 0x90, 0x98, 0x92, 0x21, 0x17, 0x8b, 0x6f, 0x7e, 0x59, 0x2a, 0x36, 0xa5, 0x46,
	0x42, 0x9c, 0x5c, 0x8c, 0x15, 0x10, 0x75, 0x20, 0x66, 0xa5, 0x04, 0x33, 0x88, 0x09, 0x08, 0x00,
	0x00, 0xff, 0xff, 0x1e, 0x3a, 0x12, 0x14, 0x76, 0x00, 0x00, 0x00,
}
